### ISSUE TITLE
Enhancement in assert_almost_equal function

### ISSUE THREAD

**Issue by chrishaegner** [mara/etl-tools#3]
One adjustment I have included in my setup is

divide abs(result2 - result1) / **abs(**result1**)** which can also be simplified to **abs(**(result2 - result1) / result1 **)**
to avoid issues with negative result1, since dividing positive by negative always results in negative numbers and thus the function always asserts.

I also corrected the typo in the description in the exception raised below. ("/" instead of "-")

**Comment by gathineou** [comment]
Hi @chrishaegner and thanks for the comment!
Please create a PR with the changes. I would also preserve the **nullif** in the percentage denominator. Thanks

**Comment by chrishaegner** [comment]
Hi @gathineou, just corrected it locally, can you give me permissions to push and create a PR?

**Comment by gathineou** [comment]
Hi Chris, just invited you as a member of Mara. You should have permissions now!

**Comment by gathineou** [comment]
Hi @chrishaegner, PR is merged so I'm closing this as well. Thanks
